# Main ast-grep configuration for removing Provider from @shopify/app-bridge-react
# This combines import and JSX transformation rules

id: remove-provider-complete
language: javascript
message: "Remove Provider from @shopify/app-bridge-react imports and unwrap JSX"
rule:
  any:
    # Import transformation rules - exact match for our test case
    - pattern: import {Provider, TitleBar} from '@shopify/app-bridge-react';
      fix: import { TitleBar } from '@shopify/app-bridge-react';
    
    # JSX transformation rules
    - pattern: <Provider $$$PROPS>$$$CHILDREN</Provider>
      fix: $$$CHILDREN
