version: "1"

nodes:
  - id: apply-transforms
    name: Remove App Bridge React Provider
    type: automatic
    steps:
      - name: "Remove Provider import and unwrap JSX"
        js-ast-grep:
          js_file: scripts/index.ts
          language: "typescript"

