version: "1"

nodes:
  - id: apply-jssg-transforms
    name: Apply JSSG Transformations
    type: automatic
    steps:
      - name: "Remove Provider from imports and unwrap JSX using JSSG"
        js-ast-grep:
          js_file: scripts/index.ts
          language: "javascript"

